# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cbindWriter <- function(pA, pB, pC) {
    invisible(.Call('bigExplore_cbindWriter', PACKAGE = 'bigExplore', pA, pB, pC))
}

chunkWriter <- function(pA, data, start, chunksize) {
    invisible(.Call('bigExplore_chunkWriter', PACKAGE = 'bigExplore', pA, data, start, chunksize))
}

bigCooksCpp <- function(pBigMat, pRes, pCooks, coeff, means, covInv) {
    invisible(.Call('bigExplore_bigCooksCpp', PACKAGE = 'bigExplore', pBigMat, pRes, pCooks, coeff, means, covInv))
}

fuzzyFileCpp <- function(pBigMat, power, var) {
    invisible(.Call('bigExplore_fuzzyFileCpp', PACKAGE = 'bigExplore', pBigMat, power, var))
}

bigLevCpp <- function(pBigMat, pLev, means, covInv) {
    invisible(.Call('bigExplore_bigLevCpp', PACKAGE = 'bigExplore', pBigMat, pLev, means, covInv))
}

biglmPredictCpp <- function(pBigMat, pPred, coeff) {
    invisible(.Call('bigExplore_biglmPredictCpp', PACKAGE = 'bigExplore', pBigMat, pPred, coeff))
}

biglmResidCpp <- function(pBigMat, pRes, pResid, coeff) {
    invisible(.Call('bigExplore_biglmResidCpp', PACKAGE = 'bigExplore', pBigMat, pRes, pResid, coeff))
}

biglmStandardCpp <- function(pBigMat, pRes, pStandard, coeff, means, covInv) {
    invisible(.Call('bigExplore_biglmStandardCpp', PACKAGE = 'bigExplore', pBigMat, pRes, pStandard, coeff, means, covInv))
}

biglmStudentCpp <- function(pBigMat, pRes, pStudent, coeff, means, covInv) {
    invisible(.Call('bigExplore_biglmStudentCpp', PACKAGE = 'bigExplore', pBigMat, pRes, pStudent, coeff, means, covInv))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('bigExplore_RcppExport_registerCCallable', PACKAGE = 'bigExplore')
})
